add to automerge job
change greater than

change if statement

attempt to fix if

debug

fix space

diff --git a/.github/workflows/automerge.yml b/.github/workflows/automerge.yml
--- a/.github/workflows/automerge.yml
+++ b/.github/workflows/automerge.yml
@@ -18,17 +18,6 @@ on:
       - completed
   status: {}
 jobs:
-  statusChecks:
-    runs-on: ubuntu-latest
-    - name: Checkout
-      uses: actions/checkout@v1
-    - name: status checker
-    env:
-      name: openservicemesh
-    run: |
-      checkSuiteID=$(curl -i -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/"$name"/osm/commits/${{GITHUB_SHA}}/check-runs | grep --after-context=2 check_suite | head -2 | grep id | awk '{print $2}')
-      countNumStatusFail=$(curl -i -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/"$name"/osm/check_suites/"$checkSuiteID"/check-runs | grep conclusion | awk '{print $2}' | grep failure| wc -l)
-      if [ $countNumStatusFail > 0 ]; then exit 1; fi
   automerge:
     runs-on: ubuntu-latest
     steps:
@@ -49,8 +38,20 @@ jobs:
         tokenURL=$(curl -i -X GET -H "Authorization: Bearer $header.$payload.$signature" -H "Accept: application/vnd.github.v3+json" https://api.github.com/app/installations | grep 'access_tokens_url' | awk '{print $2}' | sed -e 's/^"//' -e 's/",$//')
         token=$(curl -i -X POST -H "Authorization: Bearer $header.$payload.$signature" -H "Accept: application/vnd.github.v3+json" "$tokenURL" | grep 'token'| awk '{print $2}' | sed -e 's/^"//' -e 's/",$//')
         echo "GITHUB_TOKEN=$token" >> "$GITHUB_ENV"
+    - name: status checker
+      env:
+        name: openservicemesh
+      run: |
+        checkSuiteID=$(curl -i -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/$name/osm/commits/${{GITHUB_SHA}}/check-runs | grep --after-context=2 check_suite | head -2 | grep id | awk '{print $2}')
+        echo $checkSuiteID
+        countNumStatusFail=$(curl -i -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/$name/osm/check_suites/$checkSuiteID/check-runs | grep conclusion | grep failure| wc -l)
+        echo $countNumStatusFail
+        if [ $countNumStatusFail -gt 0 ]; then
+          echo "$countNumStatusFail Status Checks Failed "
+          exit 1
+        fi
     - name: automerge
-      needs: statusChecks
+      if: ${{ success() }}
       uses: "pascalgn/automerge-action@v0.13.0"
       env:
         MERGE_METHOD: "merge"
